apiVersion: v1
kind: Secret
metadata:
  name: api-secret
 
type: Opaque
 
data:
  DB_PASSWORD: QnJ1bmluaG8yOEA=         # Bruninho28@
  JWT_SECRET: c3VwZXJzZWNyZXQ=          # supersecret
  MOCK_USER_EMAIL: YWRtaW5Ab2ZpY2luYS5jb20=  # admin@oficina.com
  MOCK_USER_PASSWORD: MTIzNDU2           # 123456
  MOCK_USER_ID: MQ==                     # 1