apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:15

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: oficina

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DB_PASSWORD

          volumeMounts:
            # Dados do banco
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

            # Scripts SQL de inicialização
            - name: postgres-init
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true

      volumes:
        # PVC
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

        # ConfigMap com os SQLs
        - name: postgres-init
          configMap:
            name: postgres-init