sonar.projectKey=BrunoAmathias_TechChallengerFiap
sonar.organization=brunoamathias
sonar.token=ada0bbd41bcdf62ea505859abd00be93dd38eb55

sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info